"""Add location type and stock capability

Revision ID: 1e664d9b100d
Revises: a7770b2d5ae0
Create Date: 2026-08-25 07:33:55.752599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e664d9b100d'
down_revision = 'a7770b2d5ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('can_hold_stock', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_locations_can_hold_stock'), ['can_hold_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_location_type'), ['location_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_location_type'))
        batch_op.drop_index(batch_op.f('ix_locations_can_hold_stock'))
        batch_op.drop_column('can_hold_stock')
        batch_op.drop_column('location_type')

    # ### end Alembic commands ###
