"""Add item and location master data

Revision ID: 2c7eae80129e
Revises: 
Create Date: 2026-08-25 06:41:30.090297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7eae80129e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_parent_id'), ['parent_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_item_type_id'), ['item_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)

    op.create_table('item_identifiers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('identifier_type', sa.String(length=30), nullable=False),
    sa.Column('identifier_value', sa.String(length=100), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_identifiers_identifier_value'), ['identifier_value'], unique=True)
        batch_op.create_index(batch_op.f('ix_item_identifiers_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_identifiers_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_identifiers_identifier_value'))

    op.drop_table('item_identifiers')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_item_type_id'))
        batch_op.drop_index(batch_op.f('ix_items_is_active'))

    op.drop_table('items')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_parent_id'))
        batch_op.drop_index(batch_op.f('ix_locations_is_active'))

    op.drop_table('locations')
    op.drop_table('item_types')
    # ### end Alembic commands ###
