"""Add item images

Revision ID: 466df101c069
Revises: 9e7c02ca4401
Create Date: 2026-08-25 13:27:28.736118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466df101c069'
down_revision = '9e7c02ca4401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_images_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_images_item_id'))

    op.drop_table('item_images')
    # ### end Alembic commands ###
