"""Add inventory stock and movements

Revision ID: 9e7c02ca4401
Revises: 1e664d9b100d
Create Date: 2026-08-25 08:00:13.171620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7c02ca4401'
down_revision = '1e664d9b100d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('from_location_id', sa.BigInteger(), nullable=True),
    sa.Column('to_location_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source_quantity_before', sa.Integer(), nullable=True),
    sa.Column('source_quantity_after', sa.Integer(), nullable=True),
    sa.Column('destination_quantity_before', sa.Integer(), nullable=True),
    sa.Column('destination_quantity_after', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_inventory_movements_quantity_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_from_location_id'), ['from_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_to_location_id'), ['to_location_id'], unique=False)

    op.create_table('inventory_stock',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_stock_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'location_id', name='uq_inventory_stock_item_location')
    )
    with op.batch_alter_table('inventory_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_stock_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_stock_location_id'), ['location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_stock_location_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_stock_item_id'))

    op.drop_table('inventory_stock')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_to_location_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_from_location_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_at'))

    op.drop_table('inventory_movements')
    # ### end Alembic commands ###
